# Generated by Django 4.2.30 on 2026-05-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='locked_balance',
            field=models.FloatField(default=0, help_text='Amount still locked, not unlocked to charity'),
        ),
        migrations.AddField(
            model_name='donation',
            name='unlocked_balance',
            field=models.FloatField(default=0, help_text='Amount unlocked to charity'),
        ),
    ]
