# Generated by Django 4.2.30 on 2026-05-14 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_app', '0003_donation_stealth_address_useraccount_encrypted_kyc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='total_spent',
            field=models.FloatField(default=0, help_text='Total amount spent from unlocked funds'),
        ),
        migrations.CreateModel(
            name='CharityExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('bills', 'Bills and Utilities'), ('supplies', 'Supplies and Equipment'), ('services', 'Services and Maintenance'), ('other', 'Other Expenses')], default='other', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the expense')),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash if applicable', max_length=200, null=True)),
                ('approved_by_admin', models.BooleanField(default=False, help_text='Admin approval required for large expenses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='zakat_app.charity')),
            ],
        ),
    ]
