# Generated by Django 4.2.30 on 2026-05-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_app', '0004_charity_total_spent_charityexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='contract_time_limit_days',
            field=models.PositiveIntegerField(default=3, help_text='Days before a charity unlock request auto-approves if the donor does not respond'),
        ),
        migrations.AddField(
            model_name='fundunlockrequest',
            name='auto_approved',
            field=models.BooleanField(default=False, help_text='Automatically approved after deadline if donor did not respond'),
        ),
        migrations.AddField(
            model_name='fundunlockrequest',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
